/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapagoimpuestos.View.Empresa.ConsultarLiquidacion;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import sistemapagoimpuestos.Controller.ControladorConsultarLiquidacion;
import sistemapagoimpuestos.Dto.DTODetalleExporteLiquidacion;
import sistemapagoimpuestos.Dto.DTOExporteLiquidacion;
import sistemapagoimpuestos.Dto.DTOLiquidacionesConsultarLiquidaciones;


/**
 *
 * @author vande
 */
public class IUMostrar extends javax.swing.JDialog {
     static int sizeTable;
     double totalComision=0.0;
    /**
     * Creates new form IUMostrar
     */
    public IUMostrar(String nliquidacion) {
        initComponents();
        ControladorConsultarLiquidacion controlador = new ControladorConsultarLiquidacion();
       DTOLiquidacionesConsultarLiquidaciones dtoLiquidacion = controlador.buscardetalleLiquidacion(nliquidacion);
       
        jLabelEmpresa.setText(dtoLiquidacion.getNombreEmpresa());
        jLabelTipoImpuesto.setText(dtoLiquidacion.getNombreTipoImpuesto());
        jLabelNrodeLiquidacion.setText(nliquidacion);
        jLabelFechaLiquidacion.setText(dtoLiquidacion.getFechaHoraLiquidacion().toString());
        jLabelPeriodo.setText(dtoLiquidacion.getFechaHoraDesdeLiquidacion().toString()+" - "+dtoLiquidacion.getFechaHoraHastaLiquidacion().toString());
        
        NumberFormat nf = NumberFormat.getInstance();
            nf.setMaximumFractionDigits(3);
        jTextFieldMontoTotal.setText(nf.format(dtoLiquidacion.getTotalLiquidado()));
        DefaultTableModel model = (DefaultTableModel)jTableOperacion.getModel();
         while (model.getRowCount() > 0) {
            model.removeRow(0);}
         //if(dtoLiquidacion.getListOperacionComision().size()==0){
          //   JOptionPane.showMessageDialog(rootPane, "No se han encontrado Operaciones relacionadas a la liquidación seleccionada");}
        sizeTable = dtoLiquidacion.getListOperacionComision().size();
        for (int i = 0; i < dtoLiquidacion.getListOperacionComision().size(); i++) {
            model.addRow(new Object[]{});
            
            jTableOperacion.setValueAt(dtoLiquidacion.getListOperacionComision().get(i).getNumeroOperacion(), i, 0);
            jTableOperacion.setValueAt(dtoLiquidacion.getListOperacionComision().get(i).getFechaHoraOperacion().toString(), i, 1);
            jTableOperacion.setValueAt(dtoLiquidacion.getListOperacionComision().get(i).getNroComprobanteFactura(), i, 2);
            jTableOperacion.setValueAt(dtoLiquidacion.getListOperacionComision().get(i).getImportePagadoOperacion(), i, 3);
            jTableOperacion.setValueAt(nf.format(dtoLiquidacion.getListOperacionComision().get(i).getValorComision()), i, 4); 
            totalComision =+ dtoLiquidacion.getListOperacionComision().get(i).getValorComision();
        }
         jTextFieldMontoTotal.setText(nf.format(totalComision));
         for (int i = 0; i < (model.getRowCount()*(model.getRowCount()-1)); i++) {
          
            for (int j = 0; j <  model.getRowCount()-1; j++) {
                String d = jTableOperacion.getValueAt(j, 1).toString();
                String d2 = jTableOperacion.getValueAt(j+1, 1).toString();
                if (d.compareTo(d2)>0){ //d>d2
                model.moveRow(j, j, j+1);
                }
                
            }
        }
     /*
*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOperacion = new javax.swing.JTable();
        jLabelEmpresa = new javax.swing.JLabel();
        jLabelTipoImpuesto = new javax.swing.JLabel();
        jLabelNrodeLiquidacion = new javax.swing.JLabel();
        jLabelFechaLiquidacion = new javax.swing.JLabel();
        jLabelPeriodo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMontoTotal = new javax.swing.JTextField();
        buttonDescargar = new javax.swing.JButton();
        buttonDescargar1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Operaciones");

        jLabel1.setText("Empresa:");

        jLabel2.setText("Tipo Impuesto");

        jLabel3.setText("Nro de liquidacion");

        jLabel4.setText("Fecha liquidacion");

        jLabel5.setText("Periodo liquidado:");

        jTableOperacion = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jTableOperacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nroOperacion", "fechaOperacion", "nroComprobante", "importePagado", "montoComision"
            }
        ));
        jScrollPane2.setViewportView(jTableOperacion);

        jLabelEmpresa.setText("jLabel6");

        jLabelTipoImpuesto.setText("jLabel7");

        jLabelNrodeLiquidacion.setText("jLabel8");

        jLabelFechaLiquidacion.setText("jLabel9");

        jLabelPeriodo.setText("jLabel10");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel11.setText("Monto Comision Total");

        jTextFieldMontoTotal.setEditable(false);
        jTextFieldMontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMontoTotalActionPerformed(evt);
            }
        });

        buttonDescargar.setText("Exportar a Txt");
        buttonDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDescargarActionPerformed(evt);
            }
        });

        buttonDescargar1.setText("Exportar a Excel");
        buttonDescargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDescargar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(14, 14, 14)
                                .addComponent(jLabelNrodeLiquidacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelFechaLiquidacion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmpresa)
                                    .addComponent(jLabelTipoImpuesto)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPeriodo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(buttonDescargar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDescargar)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelTipoImpuesto))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelNrodeLiquidacion)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelFechaLiquidacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelPeriodo))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDescargar)
                    .addComponent(buttonDescargar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMontoTotalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void buttonDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDescargarActionPerformed

      DTOExporteLiquidacion dtoExporteLiquidacion = new DTOExporteLiquidacion();
      dtoExporteLiquidacion.setEmpresa(jLabelEmpresa.getText());
      dtoExporteLiquidacion.setFechaLiquidacion(jLabelFechaLiquidacion.getText());
      dtoExporteLiquidacion.setNumeroLiquidacion(jLabelNrodeLiquidacion.getText());
      dtoExporteLiquidacion.setPeriodo(jLabelPeriodo.getText());
      dtoExporteLiquidacion.setTipoImpuesto(jLabelTipoImpuesto.getText());
      dtoExporteLiquidacion.setMontoTotalComision(jTextFieldMontoTotal.getText());
      ArrayList<DTODetalleExporteLiquidacion> listDetallesExporteLiq = new ArrayList<DTODetalleExporteLiquidacion>();
       for (int i = 0; i < jTableOperacion.getRowCount(); i++) {
            DTODetalleExporteLiquidacion dto = new DTODetalleExporteLiquidacion();
            dto.setNumeroOperacion(jTableOperacion.getValueAt(i, 0).toString());
              dto.setFechaOperacion(jTableOperacion.getValueAt(i, 1).toString());
                          dto.setNumeroComprobante(jTableOperacion.getValueAt(i, 2).toString());
            dto.setImportePagado(Double.valueOf(jTableOperacion.getValueAt(i, 3).toString().replace(",", ".")));
            dto.setMontoComision(Double.valueOf(jTableOperacion.getValueAt(i, 4).toString().replace(",", ".")));
            listDetallesExporteLiq.add(dto);
        }
       dtoExporteLiquidacion.setListDetallesExporte(listDetallesExporteLiq);
       ControladorConsultarLiquidacion controlador = new ControladorConsultarLiquidacion();
       controlador.exportarLiquidacion(dtoExporteLiquidacion, "Txt");
 
    }//GEN-LAST:event_buttonDescargarActionPerformed

    private void buttonDescargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDescargar1ActionPerformed
             
      DTOExporteLiquidacion dtoExporteLiquidacion = new DTOExporteLiquidacion();
      dtoExporteLiquidacion.setEmpresa(jLabelEmpresa.getText());
      dtoExporteLiquidacion.setFechaLiquidacion(jLabelFechaLiquidacion.getText());
      dtoExporteLiquidacion.setNumeroLiquidacion(jLabelNrodeLiquidacion.getText());
      dtoExporteLiquidacion.setPeriodo(jLabelPeriodo.getText());
      dtoExporteLiquidacion.setTipoImpuesto(jLabelTipoImpuesto.getText());
      dtoExporteLiquidacion.setMontoTotalComision(jTextFieldMontoTotal.getText());
      ArrayList<DTODetalleExporteLiquidacion> listDetallesExporteLiq = new ArrayList<DTODetalleExporteLiquidacion>();
       for (int i = 0; i < jTableOperacion.getRowCount(); i++) {
            DTODetalleExporteLiquidacion dto = new DTODetalleExporteLiquidacion();
            dto.setNumeroOperacion(jTableOperacion.getValueAt(i, 0).toString());
              dto.setFechaOperacion(jTableOperacion.getValueAt(i, 1).toString());
                          dto.setNumeroComprobante(jTableOperacion.getValueAt(i, 2).toString());
            dto.setImportePagado(Double.valueOf(jTableOperacion.getValueAt(i, 3).toString().replace(",", ".")));
            dto.setMontoComision(Double.valueOf(jTableOperacion.getValueAt(i, 4).toString().replace(",", ".")));
            listDetallesExporteLiq.add(dto);
        }
       dtoExporteLiquidacion.setListDetallesExporte(listDetallesExporteLiq);
       ControladorConsultarLiquidacion controlador = new ControladorConsultarLiquidacion();
       controlador.exportarLiquidacion(dtoExporteLiquidacion, "Excel");
 
    }//GEN-LAST:event_buttonDescargar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUMostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUMostrar("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDescargar;
    private javax.swing.JButton buttonDescargar1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabelEmpresa;
    public static javax.swing.JLabel jLabelFechaLiquidacion;
    public static javax.swing.JLabel jLabelNrodeLiquidacion;
    public static javax.swing.JLabel jLabelPeriodo;
    public static javax.swing.JLabel jLabelTipoImpuesto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTableOperacion;
    public static javax.swing.JTextField jTextFieldMontoTotal;
    // End of variables declaration//GEN-END:variables
}
