package sistemapagoimpuestos.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import sistemapagoimpuestos.Controller.ControladorPagarImpuestos;
import sistemapagoimpuestos.Dto.DTOEmpresa;
import sistemapagoimpuestos.Dto.DTOTipoImpuesto;

/**
 *
 * @author lunamarcos
 */
public class IUPagarImpuesto extends javax.swing.JFrame {
    
    ControladorPagarImpuestos controlador = new ControladorPagarImpuestos();

    /**
     * Creates new form IUPagarImpuesto
     */
    public IUPagarImpuesto() {
        initComponents();
        // Agrego action listener para que se ejecute cuando cambie el valor seleccionado
        comboBox_tipoImpuesto.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                llenarComboEmpresa(buscarEmpresas(comboBox_tipoImpuesto.getSelectedItem().toString()));
            }
        });
        // Busco todos los tipoimpuestos
        llenarComboTipoImpuesto(buscarTipoImpuestos());
        // Obtengo la empresa
        llenarComboEmpresa(buscarEmpresas(comboBox_tipoImpuesto.getSelectedItem().toString()));
       
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_pagarImpuesto = new javax.swing.JLabel();
        label_tipoImpuesto = new javax.swing.JLabel();
        comboBox_tipoImpuesto = new javax.swing.JComboBox<>();
        label_empresa = new javax.swing.JLabel();
        comboBox_empresa = new javax.swing.JComboBox<>();
        label_codigo = new javax.swing.JLabel();
        textfield_codigo = new javax.swing.JTextField();
        button_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_pagarImpuesto.setText("PAGAR IMPUESTO");

        label_tipoImpuesto.setText("Tipo de Impuesto");

        comboBox_tipoImpuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_tipoImpuestoActionPerformed(evt);
            }
        });

        label_empresa.setText("Empresa");
        label_empresa.setToolTipText("");

        label_codigo.setText("Codigo pago electrónico");

        button_buscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(label_pagarImpuesto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_tipoImpuesto)
                            .addComponent(label_empresa)
                            .addComponent(label_codigo))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBox_tipoImpuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_empresa, 0, 187, Short.MAX_VALUE)
                            .addComponent(textfield_codigo))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(label_pagarImpuesto)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipoImpuesto)
                    .addComponent(comboBox_tipoImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_empresa)
                    .addComponent(comboBox_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(label_codigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textfield_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(button_buscar)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_tipoImpuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_tipoImpuestoActionPerformed

    }//GEN-LAST:event_comboBox_tipoImpuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPagarImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPagarImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPagarImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPagarImpuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPagarImpuesto().setVisible(true);
            }
        });
    }
    
    // Método para recuperar los TipoImpuesto
    public List<DTOTipoImpuesto> buscarTipoImpuestos(){
        return controlador.buscarTipoImpuestos();
    }
    
    //Método para llenar el comboBox
    public void llenarComboTipoImpuesto(List<DTOTipoImpuesto> listaDTOTipoImpuesto){
        for (int i = 0; i < listaDTOTipoImpuesto.size(); i++) {
            DTOTipoImpuesto dtoTipoImpuesto = (DTOTipoImpuesto) listaDTOTipoImpuesto.get(i);
            String nombreTipoImpuesto = dtoTipoImpuesto.getNombreDTOTipoImpuesto();
            comboBox_tipoImpuesto.addItem(nombreTipoImpuesto);
        }
    }
    
    // Método para recuperar las Empresas
    public List<DTOEmpresa> buscarEmpresas(String nombreTipoImpuesto){
        return controlador.buscarEmpresas(nombreTipoImpuesto);
    }
    
    // Método para llenar el combo de Empresa
    public void llenarComboEmpresa(List<DTOEmpresa> listaDTOEmpresa){
            for (int i = 0; i < listaDTOEmpresa.size(); i++) {
            DTOEmpresa dtoEmpresa = (DTOEmpresa) listaDTOEmpresa.get(i);
            String nombreEmpresa = dtoEmpresa.getNombreEmpresa();
            comboBox_empresa.addItem(nombreEmpresa);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_buscar;
    private javax.swing.JComboBox<String> comboBox_empresa;
    private javax.swing.JComboBox<String> comboBox_tipoImpuesto;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_empresa;
    private javax.swing.JLabel label_pagarImpuesto;
    private javax.swing.JLabel label_tipoImpuesto;
    private javax.swing.JTextField textfield_codigo;
    // End of variables declaration//GEN-END:variables
}
