package sistemapagoimpuestos.View.Admin.GestionarEmpresaAdherida;

import sistemapagoimpuestos.View.Admin.GestionarTipoImpuesto.*;
import exceptions.Excepciones;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import sistemapagoimpuestos.Controller.ControladorGestionarEmpresaAdherida;
import sistemapagoimpuestos.Dto.DTOEmpresaTipImpItem;
import sistemapagoimpuestos.Dto.DTOEmpresaTipoImpuestoItems;
import sistemapagoimpuestos.Dto.DTOItem;
import sistemapagoimpuestos.Dto.DTOTipoImpuesto;
import sistemapagoimpuestos.Dto.DtoItemOrden;
/**
 *
 * @author lunamarcos
 */
public class IUGestionarEmpresaAdheridaItemsAsociacion extends javax.swing.JFrame {

    ControladorGestionarEmpresaAdherida controlador = new ControladorGestionarEmpresaAdherida();
    private static List<DTOEmpresaTipImpItem> dTOEmpresaTipImpItemList = new ArrayList<>();

    public static List<DTOEmpresaTipImpItem> getdTOEmpresaTipImpItemList() {
        return dTOEmpresaTipImpItemList;
    }

    public static void setdTOEmpresaTipImpItemList(List<DTOEmpresaTipImpItem> dTOEmpresaTipImpItemList) {
        IUGestionarEmpresaAdheridaItemsAsociacion.dTOEmpresaTipImpItemList = dTOEmpresaTipImpItemList;
    }


    
    public static  void adddTOEmpresaTipImpItemList(DTOEmpresaTipImpItem dTOEmpresaTipImpItem){
         if(dTOEmpresaTipImpItemList==null){
            dTOEmpresaTipImpItemList = new ArrayList<>();
        }
        dTOEmpresaTipImpItemList.add(dTOEmpresaTipImpItem);
    }
    public static void removedTOEmpresaTipImpItemList(int index){
       dTOEmpresaTipImpItemList.remove(index);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
  
    public IUGestionarEmpresaAdheridaItemsAsociacion() {
        initComponents();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_empresa_item_mod = new javax.swing.JTable();
        cancel_button = new javax.swing.JButton();
        button_add_EA = new javax.swing.JButton();
        button_delete_EA = new javax.swing.JButton();
        label_fecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_modificar.setText("Guardar");
        button_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_modificarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tabla_empresa_item_mod);

        cancel_button.setText("Cancelar");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        button_add_EA.setText("Añadir");
        button_add_EA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_add_EAActionPerformed(evt);
            }
        });

        button_delete_EA.setText("Eliminar");
        button_delete_EA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_delete_EAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_delete_EA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_add_EA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 449, Short.MAX_VALUE)
                        .addComponent(label_fecha)
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_button)
                .addGap(67, 67, 67)
                .addComponent(button_modificar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(label_fecha)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(button_add_EA)
                        .addGap(57, 57, 57)
                        .addComponent(button_delete_EA)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_modificar)
                    .addComponent(cancel_button))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_modificarActionPerformed
        
        try{
            
            //controlador.modificarItemEmpresaTipoImpuesto(dTOEmpresaTipImpItem);
            this.dispose();
            controlador.iniciar();
        }catch(java.lang.NumberFormatException e){
            Excepciones.getInstance().camposRequerido(Arrays.asList("Nombre"));
        }
        
    }//GEN-LAST:event_button_modificarActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        this.dispose();
        controlador.iniciar();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void button_add_EAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_EAActionPerformed
        Vector vct = new Vector();

        vct.add(dTOEmpresaTipImpItemList.get(0).getCuitEmpresa());
        vct.add(dTOEmpresaTipImpItemList.get(0).getNombreTipoEmpresa());
        vct.add(dTOEmpresaTipImpItemList.get(0).getNombreEmpresa());
        vct.add(dTOEmpresaTipImpItemList.get(0).getNombreTipoImpuesto());
        IUGestionarEmpresaAdheridaItems pantallaGestionarTIItems = new IUGestionarEmpresaAdheridaItems(vct);
        pantallaGestionarTIItems.setLocationRelativeTo(null);
        pantallaGestionarTIItems.setVisible(true);
        //setNuevoTipoImpuesto(false);
        pantallaGestionarTIItems.setdTOEmpresaTipImpItemList(getdTOEmpresaTipImpItemList());
        this.dispose();
    }//GEN-LAST:event_button_add_EAActionPerformed

    private void button_delete_EAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_EAActionPerformed
         try {
            DefaultTableModel model = (DefaultTableModel) tabla_empresa_item_mod.getModel();
            int rowSelected = tabla_empresa_item_mod.getSelectedRow();
             removedTOEmpresaTipImpItemList(rowSelected);
            model.removeRow(rowSelected);
        } catch (ArrayIndexOutOfBoundsException e) {
            //Excepciones.getInstance().camposRequerido(Arrays.asList("Codigo"));
            Excepciones.getInstance().objetoNoSeleccionado();
        }
    }//GEN-LAST:event_button_delete_EAActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUGestionarEmpresaAdheridaItemsAsociacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUGestionarEmpresaAdheridaItemsAsociacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUGestionarEmpresaAdheridaItemsAsociacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUGestionarEmpresaAdheridaItemsAsociacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Asociacion con el controlador
                IUGestionarEmpresaAdheridaItemsAsociacion pantallaModificar = new IUGestionarEmpresaAdheridaItemsAsociacion();

            }
        });
    }
    
        public void obtenerEmpresaItems(List<DTOEmpresaTipoImpuestoItems> empresaTipoImpuestoItem) {
        
        for (DTOEmpresaTipoImpuestoItems dTOEmpresaTipoImpuestoItems : empresaTipoImpuestoItem) {
            DTOEmpresaTipImpItem dTOEmpresaTipImpItem = new DTOEmpresaTipImpItem();
            dTOEmpresaTipImpItem.setNombreEmpresa(dTOEmpresaTipoImpuestoItems.getdTOEmpresa().getNombreEmpresa());
            dTOEmpresaTipImpItem.setNombreTipoEmpresa(dTOEmpresaTipoImpuestoItems.getdTOTipoEmpresa().getNombreTipoEmpresa());
            dTOEmpresaTipImpItem.setFrecuenciaSincronizacion(dTOEmpresaTipoImpuestoItems.getFrecuenciaSincro());
            for(DTOItem dTOItem : dTOEmpresaTipoImpuestoItems.getdTOItems()){
                //dTOEmpresaTipImpItem.setFrecuenciaSincronizacion(dTOEmpresaTipoImpuestoItems);
               // dTOEmpresaTipImpItem.addItem(new DtoItemOrden(dTOItem.getNombreItem(), dTOEmpresaTipImpItem.getFrecuenciaSincronizacion()));
            }
            adddTOEmpresaTipImpItemList(dTOEmpresaTipImpItem);
        }
    }
  public void RecuperarEmpresaItems() {
        // Muestro pantalla de Consultar
        String[] columnas = {"Empresa", "Tipo Empresa", "Items"};

        DefaultTableModel dtm = new DefaultTableModel(null, columnas) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }

            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return String.class;
                    case 1:
                        return String.class;
                    case 2:
                        return int.class;
                    default:
                        return null;
                }
            }

        };

        for (DTOEmpresaTipImpItem dTOEmpresaTipImpItem : dTOEmpresaTipImpItemList) {
            Vector<Object> vect = new Vector<>();
            vect.add(dTOEmpresaTipImpItem.getNombreEmpresa());
            vect.add(dTOEmpresaTipImpItem.getNombreTipoEmpresa());
            vect.add(dTOEmpresaTipImpItem.concatItems());
            dtm.addRow(vect);
        }

        DefaultTableCellRenderer r = new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(JLabel.CENTER);
                return this;
            }
        };
        tabla_empresa_item_mod.setModel(dtm);
        tabla_empresa_item_mod.getColumnModel().getColumn(0).setCellRenderer(r);
        tabla_empresa_item_mod.getColumnModel().getColumn(1).setCellRenderer(r);
    }

       
        
    // Getters

    public JLabel getLabel_fecha() {
        return label_fecha;
    }

    public void setLabel_fecha(JLabel label_fecha) {
        this.label_fecha = label_fecha;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add_EA;
    private javax.swing.JButton button_delete_EA;
    private javax.swing.JButton button_modificar;
    private javax.swing.JButton cancel_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JTable tabla_empresa_item_mod;
    // End of variables declaration//GEN-END:variables
}
