package Entity;
// Generated 25/09/2017 11:49:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Claro generated by hbm2java
 */
@Entity
@Table(name="claro"
    ,catalog="empresas"
)
public class Claro  implements java.io.Serializable {


     private String codigo;
     private String nombreServicio;
     private Double montoTotal;
     private Double montoPagado;
     private String status;
     private Integer nroTelefono;
     private Date vencimiento;

    public Claro() {
    }

	

    public Claro(String codigo, String nombreServicio, Double montoTotal, Double montoPagado, String status, Integer nroTelefono, Date vencimiento) {
        this.codigo = codigo;
        this.nombreServicio = nombreServicio;
        this.montoTotal = montoTotal;
        this.montoPagado = montoPagado;
        this.status = status;
        this.nroTelefono = nroTelefono;
        this.vencimiento = vencimiento;
    }
    
    
    @Id     
    @Column(name="codigo", unique = true)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombreServicio")
    public String getNombreServicio() {
        return this.nombreServicio;
    }
    
    public void setNombreServicio(String nombreServicio) {
        this.nombreServicio = nombreServicio;
    }

    
    @Column(name="montoTotal", precision=22, scale=0)
    public Double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }

    
    @Column(name="montoPagado", precision=22, scale=0)
    public Double getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(Double montoPagado) {
        this.montoPagado = montoPagado;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="nroTelefono")
    public Integer getNroTelefono() {
        return this.nroTelefono;
    }
    
    public void setNroTelefono(Integer nroTelefono) {
        this.nroTelefono = nroTelefono;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="vencimiento", length=19)
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }




}


