package Entity;
// Generated 25/09/2017 11:49:31 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Claro generated by hbm2java
 */
@Entity
@Table(name="claro"
    ,catalog="empresas"
)
public class Claro  implements java.io.Serializable {

    private int nroFactura;
     private String codigo;
     private String nombreServicio;
     private Double montoTotal;
     private Double montoPagado;
     private Double montoMinimo;
     private String status;
     private Integer nroTelefono;
     private Date vencimiento;
     private String codigoCP;
    public Claro() {
    }

	

    public Claro(String codigo, String nombreServicio, Double montoTotal, Double montoPagado, String status, Integer nroTelefono, Date vencimiento) {
        this.codigo = codigo;
        this.nombreServicio = nombreServicio;
        this.montoTotal = montoTotal;
        this.montoMinimo = montoPagado;
        this.status = status;
        this.nroTelefono = nroTelefono;
        this.vencimiento = vencimiento;
    }
    
    
    @Id
    @Column(name="nroFactura")
    public int getNroFactura() {
        return nroFactura;
    }

    public void setNroFactura(int id) {
        this.nroFactura = id;
    }
    
    
    @Column(name="codigo")
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombreServicio")
    public String getNombreServicio() {
        return this.nombreServicio;
    }
    
    public void setNombreServicio(String nombreServicio) {
        this.nombreServicio = nombreServicio;
    }

    
    @Column(name="montoTotal", precision=22, scale=0)
    public Double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }

    
    @Column(name="montoMinimo", precision=22, scale=0)
    public Double getMontoMinimo() {
        return this.montoMinimo;
    }
    
    public void setMontoMinimo(Double montoMinimo) {
        this.montoMinimo = montoMinimo;
    }

    
    @Column(name="status")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="nroTelefono")
    public Integer getNroTelefono() {
        return this.nroTelefono;
    }
    
    public void setNroTelefono(Integer nroTelefono) {
        this.nroTelefono = nroTelefono;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="vencimiento", length=19)
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }

    @Column(name="montoPagado")
    public Double getMontoPagado() {
        return montoPagado;
    }
    public void setMontoPagado(Double montoPagado) {
        this.montoPagado = montoPagado;
    }
    @Column(name="codigoCP")
    public String getCodigoCP() {
        return codigoCP;
    }

    public void setCodigoCP(String codigoCP) {
        this.codigoCP = codigoCP;
    }

    




}


